# kafka
# redis
# adminer
# mariadb

services:
  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    environment:
      KAFKA_NODE_ID: 1
      CLUSTER_ID: "542d98fc-271b-4b5f-b5db-fbf88b32acb9"
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:kafka:9092,PLAINTEXT_HOST://:localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MION_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    command: >
      bash -c "
        if [ ! -f /tmp/kraft-combined-logs/meta.proerties ]; then
          echo 'Formatting storage directory...'
          kafka-storage format \
            --ignore-formatted \
            --cluster-id=542d98fc-271b-4b5f-b5db-fbf88b32acb9 \
            --config /etc/kafka/kafka.properties
        fi
      /etc/confluent/docker/run
      "
    networks:
      - local

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8888:8080
    restart: unless-stopped
    environment:
      KAFKA_CLUSTER_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTER_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - kafka
    networks:
      - local

networks:
  local:
